all:
  hosts:
    node-2:
      ansible_connection: ssh
      ansible_user: vagrant
  children:
    kubeMaster:
      hosts:
        master:
          ansible_connection: ssh
          ansible_user: vagrant
          ansible_become: yes
    kubeNodes:
      hosts:
        node-1:
          ansible_connection: ssh
          ansible_user: vagrant

    sudhir_machines:
      hosts:
        sudhir-desktop:
          ansible_user: sudhir
          ansible_become: yes
          ansible_become_password: "{{ansible_su_password}}"
          ansible_host: www.yadavsudhir.com
          ansible_port: 22