- name: Install certificates
  hosts: sudhir_machines
  gather_facts: true
  vars:
    domains:
      - www.yadavsudhir.com
      - gitlab.yadavsudhir.com
      - apps.yadavsudhir.com
      - harbor.yadavsudhir.com
      - kiali.yadavsudhir.com
      - jagar.yadavsudhir.com
      - grafana.yadavsudhir.com
      - prometheus.yadavsudhir.com
  tags:
    - step3
  roles:
    - copy-certificates
    - restart-nginx