- name: Get ec2 instance id by its tag name dummy
  ec2_instance_facts:
    aws_access_key: "{{ec2_access_key}}"
    aws_secret_key: "{{ec2_secret_key}}"
    region: "{{region}}"
    filters:
      "tag:name": dummy
      instance-state-name: [ "running" ]
  register: ec2_list


- name: Terminate Any running Instances
  ec2:
    state: 'absent'
    aws_access_key: "{{ec2_access_key}}"
    aws_secret_key: "{{ec2_secret_key}}"
    region: "{{region}}"
    instance_ids: "{{item.instance_id}}"
  with_items: "{{ec2_list.instances}}"